<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OlogySocialBundleEntityChannelProxy extends \Ology\SocialBundle\Entity\Channel implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getSubscriptions()
    {
        $this->__load();
        return parent::getSubscriptions();
    }

    public function setSubscriptions($subscriptions)
    {
        $this->__load();
        return parent::setSubscriptions($subscriptions);
    }

    public function getSpecialTitle()
    {
        $this->__load();
        return parent::getSpecialTitle();
    }

    public function setSpecialTitle($specialTitle)
    {
        $this->__load();
        return parent::setSpecialTitle($specialTitle);
    }

    public function getDisplay()
    {
        $this->__load();
        return parent::getDisplay();
    }

    public function getVideo()
    {
        $this->__load();
        return parent::getVideo();
    }

    public function setVideo($v)
    {
        $this->__load();
        return parent::setVideo($v);
    }

    public function getImageLogo()
    {
        $this->__load();
        return parent::getImageLogo();
    }

    public function getImageTitle()
    {
        $this->__load();
        return parent::getImageTitle();
    }

    public function getManagedBy()
    {
        $this->__load();
        return parent::getManagedBy();
    }

    public function setImageLogo($i)
    {
        $this->__load();
        return parent::setImageLogo($i);
    }

    public function setImageTitle($i)
    {
        $this->__load();
        return parent::setImageTitle($i);
    }

    public function setManagedBy($i)
    {
        $this->__load();
        return parent::setManagedBy($i);
    }

    public function setDisplay($display)
    {
        $this->__load();
        return parent::setDisplay($display);
    }

    public function getStub()
    {
        $this->__load();
        return parent::getStub();
    }

    public function getAd0()
    {
        $this->__load();
        return parent::getAd0();
    }

    public function getAd1()
    {
        $this->__load();
        return parent::getAd1();
    }

    public function getAd2()
    {
        $this->__load();
        return parent::getAd2();
    }

    public function getAd3()
    {
        $this->__load();
        return parent::getAd3();
    }

    public function getAd4()
    {
        $this->__load();
        return parent::getAd4();
    }

    public function getAd5()
    {
        $this->__load();
        return parent::getAd5();
    }

    public function getAd6()
    {
        $this->__load();
        return parent::getAd6();
    }

    public function setAd0($ad)
    {
        $this->__load();
        return parent::setAd0($ad);
    }

    public function setAd1($ad)
    {
        $this->__load();
        return parent::setAd1($ad);
    }

    public function setAd2($ad)
    {
        $this->__load();
        return parent::setAd2($ad);
    }

    public function setAd3($ad)
    {
        $this->__load();
        return parent::setAd3($ad);
    }

    public function setAd4($ad)
    {
        $this->__load();
        return parent::setAd4($ad);
    }

    public function setAd5($ad)
    {
        $this->__load();
        return parent::setAd5($ad);
    }

    public function setAd6($ad)
    {
        $this->__load();
        return parent::setAd6($ad);
    }

    public function setStub($s)
    {
        $this->__load();
        return parent::setStub($s);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setSpecialPost1(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setSpecialPost1($featuredPost);
    }

    public function setSpecialPost2(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setSpecialPost2($featuredPost);
    }

    public function setSpecialPost3(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setSpecialPost3($featuredPost);
    }

    public function setFeaturedPost1(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setFeaturedPost1($featuredPost);
    }

    public function setFeaturedPost2(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setFeaturedPost2($featuredPost);
    }

    public function setFeaturedPost3(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setFeaturedPost3($featuredPost);
    }

    public function setFeaturedPost4(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setFeaturedPost4($featuredPost);
    }

    public function setFeaturedPost5(\Ology\SocialBundle\Entity\Post $featuredPost)
    {
        $this->__load();
        return parent::setFeaturedPost5($featuredPost);
    }

    public function getFeaturedPost1()
    {
        $this->__load();
        return parent::getFeaturedPost1();
    }

    public function getSpecialPost1()
    {
        $this->__load();
        return parent::getSpecialPost1();
    }

    public function getSpecialPost2()
    {
        $this->__load();
        return parent::getSpecialPost2();
    }

    public function getSpecialPost3()
    {
        $this->__load();
        return parent::getSpecialPost3();
    }

    public function getSpecialPost1id()
    {
        $this->__load();
        return parent::getSpecialPost1id();
    }

    public function getSpecialPost2id()
    {
        $this->__load();
        return parent::getSpecialPost2id();
    }

    public function getSpecialPost3id()
    {
        $this->__load();
        return parent::getSpecialPost3id();
    }

    public function getFeaturedPost1id()
    {
        $this->__load();
        return parent::getFeaturedPost1id();
    }

    public function getFeaturedPost2id()
    {
        $this->__load();
        return parent::getFeaturedPost2id();
    }

    public function getFeaturedPost3id()
    {
        $this->__load();
        return parent::getFeaturedPost3id();
    }

    public function getFeaturedPost4id()
    {
        $this->__load();
        return parent::getFeaturedPost4id();
    }

    public function getFeaturedPost5id()
    {
        $this->__load();
        return parent::getFeaturedPost5id();
    }

    public function getFeaturedPost2()
    {
        $this->__load();
        return parent::getFeaturedPost2();
    }

    public function getFeaturedPost3()
    {
        $this->__load();
        return parent::getFeaturedPost3();
    }

    public function getFeaturedPost4()
    {
        $this->__load();
        return parent::getFeaturedPost4();
    }

    public function getFeaturedPost5()
    {
        $this->__load();
        return parent::getFeaturedPost5();
    }

    public function setSpecialPost1id($id)
    {
        $this->__load();
        return parent::setSpecialPost1id($id);
    }

    public function setSpecialPost2id($id)
    {
        $this->__load();
        return parent::setSpecialPost2id($id);
    }

    public function setSpecialPost3id($id)
    {
        $this->__load();
        return parent::setSpecialPost3id($id);
    }

    public function setFeaturedPost1id($id)
    {
        $this->__load();
        return parent::setFeaturedPost1id($id);
    }

    public function setFeaturedPost2id($id)
    {
        $this->__load();
        return parent::setFeaturedPost2id($id);
    }

    public function setFeaturedPost3id($id)
    {
        $this->__load();
        return parent::setFeaturedPost3id($id);
    }

    public function setFeaturedPost4id($id)
    {
        $this->__load();
        return parent::setFeaturedPost4id($id);
    }

    public function setFeaturedPost5id($id)
    {
        $this->__load();
        return parent::setFeaturedPost5id($id);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'imageLogo', 'imageTitle', 'name', 'stub', 'ad0', 'ad1', 'ad2', 'ad3', 'ad4', 'ad5', 'ad6', 'display', 'video', 'specialTitle', 'managedBy', 'featuredPost1', 'featuredPost2', 'featuredPost3', 'featuredPost4', 'featuredPost5', 'specialPost1', 'specialPost2', 'specialPost3', 'subscriptions');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}