<?php

namespace Ology\SocialBundle\DAO;

use Doctrine\ORM\EntityRepository;

/**
 * OlogyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OlogyRepository extends EntityRepository
{
}